#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pyglet.window import key

#
# Kody klawiszy zmieniających wielkość liter
#
pyglet_shift_code = key.MOD_SHIFT
pyglet_capslock_code = key.MOD_CAPSLOCK

#
# Mapowanie klawiszy z pygleta na stringi ascii
#
pyglet_key_mapping = {
    key.MOD_SHIFT      : 'shift',
    key.MOD_CTRL       : 'ctrl',
    key.MOD_ALT        : 'alt',
    key.MOD_CAPSLOCK   : 'capslock',
    key.MOD_NUMLOCK    : 'numlock',
    key.MOD_WINDOWS    : 'windows',
    key.MOD_COMMAND    : 'command',
    key.MOD_OPTION     : 'option',
    key.MOD_SCROLLLOCK : 'scrolllock',
    key.MOD_ACCEL      : 'accel',

    key.BACKSPACE      : 'backspace',
    key.TAB            : 'tab',
    key.LINEFEED       : 'linefeed',
    key.CLEAR          : 'clear',
    key.RETURN         : 'return',
    key.ENTER          : 'enter',
    key.PAUSE          : 'pause',
    key.SCROLLLOCK     : 'scrolllock',
    key.SYSREQ         : 'sysreq',
    key.ESCAPE         : 'escape',
    key.HOME           : 'home',
    key.LEFT           : 'left',
    key.UP             : 'up',
    key.RIGHT          : 'right',
    key.DOWN           : 'down',
    key.PAGEUP         : 'pageup',
    key.PAGEDOWN       : 'pagedown',
    key.END            : 'end',
    key.BEGIN          : 'begin',
    key.DELETE         : 'delete',
    key.SELECT         : 'select',
    key.PRINT          : 'print',
    key.EXECUTE        : 'execute',
    key.INSERT         : 'insert',
    key.UNDO           : 'undo',
    key.REDO           : 'redo',
    key.MENU           : 'menu',
    key.FIND           : 'find',
    key.CANCEL         : 'cancel',
    key.HELP           : 'help',
    key.BREAK          : 'break',
    key.MODESWITCH     : 'modeswitch',
    key.SCRIPTSWITCH   : 'scriptswitch',
    
    key.NUMLOCK        : 'numlock',
    key.NUM_SPACE      : 'num_space',
    key.NUM_TAB        : 'num_tab',
    key.NUM_ENTER      : 'num_enter',
    key.NUM_F1         : 'num_f1',
    key.NUM_F2         : 'num_f2',
    key.NUM_F3         : 'num_f3',
    key.NUM_F4         : 'num_f4',
    key.NUM_HOME       : 'num_home',
    key.NUM_LEFT       : 'num_left',
    key.NUM_UP         : 'num_up',
    key.NUM_RIGHT      : 'num_right',
    key.NUM_DOWN       : 'num_down',
    key.NUM_PRIOR      : 'num_prior',
    key.NUM_PAGE_UP    : 'num_page_up',
    key.NUM_NEXT       : 'num_next',
    key.NUM_PAGE_DOWN  : 'num_page_down',
    key.NUM_END        : 'num_end',
    key.NUM_BEGIN      : 'num_begin',
    key.NUM_INSERT     : 'num_insert',
    key.NUM_DELETE     : 'num_delete',
    key.NUM_EQUAL      : 'num_equal',
    key.NUM_MULTIPLY   : 'num_multiply',
    key.NUM_ADD        : 'num_add',
    key.NUM_SEPARATOR  : 'num_separator',
    key.NUM_SUBTRACT   : 'num_subtract',
    key.NUM_DECIMAL    : 'num_decimal',
    key.NUM_DIVIDE     : 'num_divide',
    key.NUM_0          : 'num_0',
    key.NUM_1          : 'num_1',
    key.NUM_2          : 'num_2',
    key.NUM_3          : 'num_3',
    key.NUM_4          : 'num_4',
    key.NUM_5          : 'num_5',
    key.NUM_6          : 'num_6',
    key.NUM_7          : 'num_7',
    key.NUM_8          : 'num_8',
    key.NUM_9          : 'num_9',
    
    key.F1             : 'F1',
    key.F2             : 'F2',
    key.F3             : 'F3',
    key.F4             : 'F4',
    key.F5             : 'F5',
    key.F6             : 'F6',
    key.F7             : 'F7',
    key.F8             : 'F8',
    key.F9             : 'F9',
    key.F10            : 'F10',
    key.F11            : 'F11',
    key.F12            : 'F12',
    key.F13            : 'F13',
    key.F14            : 'F14',
    key.F15            : 'F15',
    key.F16            : 'F16',
    
    key.LSHIFT         : 'lshift',
    key.RSHIFT         : 'rshift',
    key.LCTRL          : 'lctrl',
    key.RCTRL          : 'rctrl',
    key.CAPSLOCK       : 'capslock',
    key.LMETA          : 'lmeta',
    key.RMETA          : 'rmeta',
    key.LALT           : 'lalt',
    key.RALT           : 'ralt',
    key.LWINDOWS       : 'lwindows',
    key.RWINDOWS       : 'rwindows',
    key.LCOMMAND       : 'lcommand',
    key.RCOMMAND       : 'rcommand',
    key.LOPTION        : 'loption',
    key.ROPTION        : 'roption',
    key.SPACE          : 'space',
    key.EXCLAMATION    : 'exclamation',
    key.DOUBLEQUOTE    : 'doublequote',
    key.HASH           : 'hash',
    key.POUND          : 'pound',
    key.DOLLAR         : 'dollar',
    key.PERCENT        : 'percent',
    key.AMPERSAND      : 'ampersand',
    key.APOSTROPHE     : 'apostrophe',
    key.PARENLEFT      : 'parenleft',
    key.PARENRIGHT     : 'parenright',
    key.ASTERISK       : 'asterisk',
    key.PLUS           : 'plus',
    key.COMMA          : 'comma',
    key.MINUS          : 'minus',
    key.PERIOD         : 'period',
    key.SLASH          : 'slash',
    key.COLON          : 'colon',
    key.SEMICOLON      : 'semicolon',
    key.LESS           : 'less',
    key.EQUAL          : 'equal',
    key.GREATER        : 'greater',
    key.QUESTION       : 'question',
    key.AT             : 'at',
    key.BRACKETLEFT    : 'bracketleft',
    key.BACKSLASH      : 'backslash',
    key.BRACKETRIGHT   : 'bracketright',
    key.ASCIICIRCUM    : 'asciicircum',
    key.UNDERSCORE     : 'underscore',
    key.GRAVE          : 'grave',
    key.QUOTELEFT      : 'quoteleft',
    
    key.A              : 'a',
    key.B              : 'b',
    key.C              : 'c',
    key.D              : 'd',
    key.E              : 'e',
    key.F              : 'f',
    key.G              : 'g',
    key.H              : 'h',
    key.I              : 'i',
    key.J              : 'j',
    key.K              : 'k',
    key.L              : 'l',
    key.M              : 'm',
    key.N              : 'n',
    key.O              : 'o',
    key.P              : 'p',
    key.Q              : 'q',
    key.R              : 'r',
    key.S              : 's',
    key.T              : 't',
    key.U              : 'u',
    key.V              : 'v',
    key.W              : 'w',
    key.X              : 'x',
    key.Y              : 'y',
    key.Z              : 'z',
    
    key.BRACELEFT      : '{',
    key.BAR            : 'bar',
    key.BRACERIGHT     : '}',
    key.ASCIITILDE     : '~',
}
